
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgenciaInterno", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgenciaInterno {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editarPassagem", targetNamespace = "http://service/", className = "service.EditarPassagem")
    @ResponseWrapper(localName = "editarPassagemResponse", targetNamespace = "http://service/", className = "service.EditarPassagemResponse")
    @Action(input = "http://service/AgenciaInterno/editarPassagemRequest", output = "http://service/AgenciaInterno/editarPassagemResponse")
    public void editarPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Passagem arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.Passagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarPassagens", targetNamespace = "http://service/", className = "service.ListarPassagens")
    @ResponseWrapper(localName = "listarPassagensResponse", targetNamespace = "http://service/", className = "service.ListarPassagensResponse")
    @Action(input = "http://service/AgenciaInterno/listarPassagensRequest", output = "http://service/AgenciaInterno/listarPassagensResponse")
    public List<Passagem> listarPassagens();

    /**
     * 
     * @return
     *     returns java.util.List<service.Usuario>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getTodosUsuarios", targetNamespace = "http://service/", className = "service.GetTodosUsuarios")
    @ResponseWrapper(localName = "getTodosUsuariosResponse", targetNamespace = "http://service/", className = "service.GetTodosUsuariosResponse")
    @Action(input = "http://service/AgenciaInterno/getTodosUsuariosRequest", output = "http://service/AgenciaInterno/getTodosUsuariosResponse")
    public List<Usuario> getTodosUsuarios();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editarVoo", targetNamespace = "http://service/", className = "service.EditarVoo")
    @ResponseWrapper(localName = "editarVooResponse", targetNamespace = "http://service/", className = "service.EditarVooResponse")
    @Action(input = "http://service/AgenciaInterno/editarVooRequest", output = "http://service/AgenciaInterno/editarVooResponse")
    public void editarVoo(
        @WebParam(name = "arg0", targetNamespace = "")
        Voo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editarCidade", targetNamespace = "http://service/", className = "service.EditarCidade")
    @ResponseWrapper(localName = "editarCidadeResponse", targetNamespace = "http://service/", className = "service.EditarCidadeResponse")
    @Action(input = "http://service/AgenciaInterno/editarCidadeRequest", output = "http://service/AgenciaInterno/editarCidadeResponse")
    public void editarCidade(
        @WebParam(name = "arg0", targetNamespace = "")
        Cidade arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarCidade", targetNamespace = "http://service/", className = "service.SalvarCidade")
    @ResponseWrapper(localName = "salvarCidadeResponse", targetNamespace = "http://service/", className = "service.SalvarCidadeResponse")
    @Action(input = "http://service/AgenciaInterno/salvarCidadeRequest", output = "http://service/AgenciaInterno/salvarCidadeResponse")
    public void salvarCidade(
        @WebParam(name = "arg0", targetNamespace = "")
        Cidade arg0);

    /**
     * 
     * @return
     *     returns java.util.List<service.Cidade>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listarCidades", targetNamespace = "http://service/", className = "service.ListarCidades")
    @ResponseWrapper(localName = "listarCidadesResponse", targetNamespace = "http://service/", className = "service.ListarCidadesResponse")
    @Action(input = "http://service/AgenciaInterno/listarCidadesRequest", output = "http://service/AgenciaInterno/listarCidadesResponse")
    public List<Cidade> listarCidades();

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "salvarVoo", targetNamespace = "http://service/", className = "service.SalvarVoo")
    @ResponseWrapper(localName = "salvarVooResponse", targetNamespace = "http://service/", className = "service.SalvarVooResponse")
    @Action(input = "http://service/AgenciaInterno/salvarVooRequest", output = "http://service/AgenciaInterno/salvarVooResponse")
    public void salvarVoo(
        @WebParam(name = "arg0", targetNamespace = "")
        Voo arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "editarUsuario", targetNamespace = "http://service/", className = "service.EditarUsuario")
    @ResponseWrapper(localName = "editarUsuarioResponse", targetNamespace = "http://service/", className = "service.EditarUsuarioResponse")
    @Action(input = "http://service/AgenciaInterno/editarUsuarioRequest", output = "http://service/AgenciaInterno/editarUsuarioResponse")
    public void editarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0);

}
