
package service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AgenciaService", targetNamespace = "http://service/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AgenciaService {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "venderPassagem", targetNamespace = "http://service/", className = "service.VenderPassagem")
    @ResponseWrapper(localName = "venderPassagemResponse", targetNamespace = "http://service/", className = "service.VenderPassagemResponse")
    @Action(input = "http://service/AgenciaService/venderPassagemRequest", output = "http://service/AgenciaService/venderPassagemResponse")
    public boolean venderPassagem(
        @WebParam(name = "arg0", targetNamespace = "")
        Voo arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        Usuario arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Voo>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getVoosPorData", targetNamespace = "http://service/", className = "service.GetVoosPorData")
    @ResponseWrapper(localName = "getVoosPorDataResponse", targetNamespace = "http://service/", className = "service.GetVoosPorDataResponse")
    @Action(input = "http://service/AgenciaService/getVoosPorDataRequest", output = "http://service/AgenciaService/getVoosPorDataResponse")
    public List<Voo> getVoosPorData(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<service.Passagem>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getPassagensPorData", targetNamespace = "http://service/", className = "service.GetPassagensPorData")
    @ResponseWrapper(localName = "getPassagensPorDataResponse", targetNamespace = "http://service/", className = "service.GetPassagensPorDataResponse")
    @Action(input = "http://service/AgenciaService/getPassagensPorDataRequest", output = "http://service/AgenciaService/getPassagensPorDataResponse")
    public List<Passagem> getPassagensPorData(
        @WebParam(name = "arg0", targetNamespace = "")
        XMLGregorianCalendar arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getNomeUsuario", targetNamespace = "http://service/", className = "service.GetNomeUsuario")
    @ResponseWrapper(localName = "getNomeUsuarioResponse", targetNamespace = "http://service/", className = "service.GetNomeUsuarioResponse")
    @Action(input = "http://service/AgenciaService/getNomeUsuarioRequest", output = "http://service/AgenciaService/getNomeUsuarioResponse")
    public String getNomeUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns service.Usuario
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getUsuario", targetNamespace = "http://service/", className = "service.GetUsuario")
    @ResponseWrapper(localName = "getUsuarioResponse", targetNamespace = "http://service/", className = "service.GetUsuarioResponse")
    @Action(input = "http://service/AgenciaService/getUsuarioRequest", output = "http://service/AgenciaService/getUsuarioResponse")
    public Usuario getUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "salvarUsuario", targetNamespace = "http://service/", className = "service.SalvarUsuario")
    @ResponseWrapper(localName = "salvarUsuarioResponse", targetNamespace = "http://service/", className = "service.SalvarUsuarioResponse")
    @Action(input = "http://service/AgenciaService/salvarUsuarioRequest", output = "http://service/AgenciaService/salvarUsuarioResponse")
    public boolean salvarUsuario(
        @WebParam(name = "arg0", targetNamespace = "")
        Usuario arg0);

}
