
package service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AgenciaInternaServiceService", targetNamespace = "http://service/", wsdlLocation = "http://localhost:8080/SigPassagensPOS/AgenciaInternaServiceService?WSDL")
public class AgenciaInternaServiceService
    extends Service
{

    private final static URL AGENCIAINTERNASERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException AGENCIAINTERNASERVICESERVICE_EXCEPTION;
    private final static QName AGENCIAINTERNASERVICESERVICE_QNAME = new QName("http://service/", "AgenciaInternaServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/SigPassagensPOS/AgenciaInternaServiceService?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        AGENCIAINTERNASERVICESERVICE_WSDL_LOCATION = url;
        AGENCIAINTERNASERVICESERVICE_EXCEPTION = e;
    }

    public AgenciaInternaServiceService() {
        super(__getWsdlLocation(), AGENCIAINTERNASERVICESERVICE_QNAME);
    }

    public AgenciaInternaServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), AGENCIAINTERNASERVICESERVICE_QNAME, features);
    }

    public AgenciaInternaServiceService(URL wsdlLocation) {
        super(wsdlLocation, AGENCIAINTERNASERVICESERVICE_QNAME);
    }

    public AgenciaInternaServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, AGENCIAINTERNASERVICESERVICE_QNAME, features);
    }

    public AgenciaInternaServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AgenciaInternaServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AgenciaInterno
     */
    @WebEndpoint(name = "AgenciaInternoPort")
    public AgenciaInterno getAgenciaInternoPort() {
        return super.getPort(new QName("http://service/", "AgenciaInternoPort"), AgenciaInterno.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AgenciaInterno
     */
    @WebEndpoint(name = "AgenciaInternoPort")
    public AgenciaInterno getAgenciaInternoPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service/", "AgenciaInternoPort"), AgenciaInterno.class, features);
    }

    private static URL __getWsdlLocation() {
        if (AGENCIAINTERNASERVICESERVICE_EXCEPTION!= null) {
            throw AGENCIAINTERNASERVICESERVICE_EXCEPTION;
        }
        return AGENCIAINTERNASERVICESERVICE_WSDL_LOCATION;
    }

}
